// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoqAXypH9GehDc6Z6kvZaRp-7-AHVCKIk',
    appId: '1:212687920836:web:bdf457ba615ad818387391',
    messagingSenderId: '212687920836',
    projectId: 'afarms-75055',
    authDomain: 'afarms-75055.firebaseapp.com',
    storageBucket: 'afarms-75055.appspot.com',
    measurementId: 'G-KHFLEM67EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt330Xn89F56m2n0CkrsWBZTfWche0_yw',
    appId: '1:212687920836:android:2bf27653a3a9ac94387391',
    messagingSenderId: '212687920836',
    projectId: 'afarms-75055',
    storageBucket: 'afarms-75055.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC90al4xFCJFkp4Wz4tlK3vy-5h8THNGyQ',
    appId: '1:212687920836:ios:9553972c91f32534387391',
    messagingSenderId: '212687920836',
    projectId: 'afarms-75055',
    storageBucket: 'afarms-75055.appspot.com',
    iosClientId: '212687920836-k090mtf0k0hauqcinvu7p6gr13evelua.apps.googleusercontent.com',
    iosBundleId: 'com.example.afarms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC90al4xFCJFkp4Wz4tlK3vy-5h8THNGyQ',
    appId: '1:212687920836:ios:9553972c91f32534387391',
    messagingSenderId: '212687920836',
    projectId: 'afarms-75055',
    storageBucket: 'afarms-75055.appspot.com',
    iosClientId: '212687920836-k090mtf0k0hauqcinvu7p6gr13evelua.apps.googleusercontent.com',
    iosBundleId: 'com.example.afarms',
  );
}
